root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "npm run build:assets && cd frontend && npm run build && cd ..  && go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html","jsx","json","css","scss"]
  exclude_dir = ["tmp", "vendor", "testdata", "frontend/node_modules","node_modules", "public"]
  include_dir = []
  exclude_file = [tzlev]
  log = "build-errors.log"
  delay = 1000
  stop_on_error = true
  send_interrupt = false
  kill_delay = "0s"

[misc]
  clean_on_exit = false

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
